controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      critics:
        - RotateToGoal
        - Oscillation
        - ObstacleFootprint
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

      # Below are typical params
      base_frame_id: base_link
      global_frame_id: map
      odom_frame_id: odom

      min_vel_x: 0.0
      max_vel_x: 0.5
      min_vel_theta: -1.0
      max_vel_theta: 1.0

      vx_samples: 10
      vtheta_samples: 20

      acc_lim_x: 1.0
      acc_lim_theta: 2.0

      obstacle_radius: 0.22
      footprint_model:
        type: "circle"
        radius: 0.22
